// Scripted pipeline

node {
    stage('preperation'){
        echo 'cloning repo'
        git url:'https://github.com/hamzaProgrammer/temp-jenkins.git',branch:'main'
    }
    stage('test'){
        echo 'runing test cases'
        nodejs(nodeJSInstallationName: 'Node 16') {
            sh 'npm i -D'
            sh 'npm run test'
        }
    }
    stage('building'){
        echo 'building image'
        sh 'docker build -t hamza78674/pipelinedemo:${BUILD_NUMBER} .'
    }
    stage('deploy to docker hub'){
        echo 'docker logging in'
        // withCredentials([usernamePassword(credentialsId: 'amazon', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
        
        // }
        sh 'docker login -u hamza78674 -p hamza78674'
        sh 'docker image push hamza78674/pipelinedemo:${BUILD_NUMBER}'
    }
    stage("clean up"){
        sh 'docker logout'
    }
}